[build]
command = 'hugo'
publish = 'public'
publishDir = "docs"

[build.environment]
HUGO_VERSION = '0.151.0'

[context]
[context.branch-deploy]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.deploy-preview]
command = 'hugo -F -b $DEPLOY_PRIME_URL'

[context.production]
[context.production.environment]
HUGO_ENV = 'production'
